name: hamason
description: An app build with the stacked framework
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  dio: ^5.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  infinite_scroll_pagination: ^3.2.0
  json_annotation: ^4.8.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  stacked: ^3.2.2
  stacked_services: ^1.0.2

dev_dependencies:
  build_runner: ^2.2.0  
  flutter_gen_runner: ^5.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mockito: ^5.4.0
  retrofit_generator: ^6.0.0+1
  stacked_generator: ^1.3.3

flutter_gen:
  output: lib/core/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700